#!/bin/bash
banana() {
  ./run.sh MemdiskTest.img
}
list_descendants ()
{
  local children=$(ps -o pid= --ppid "$1")
  
  for pid in $children
  do
    list_descendants "$pid"
  done
  
  echo "$children"
}
handle() {
  FOUND=0
  while IFS= read -s -r -u "$1" line
  do
    echo "$line" # make sure the output is still printed on screen
    if [[ $line == *"SUCCESS"* ]]
    then
      echo "--> TEST SUCCESSFUL:" ${@:2}
      FOUND=1
      break
    fi
    # to prevent hang forever, find panics
    if [[ $line == *"PANIC"* ]]
    then
      echo "--> TEST FAILED:" ${@:2}
      break
    fi
  done
  sudo kill $(list_descendants ${bananafd_PID})
  # exit with error code for failure
  if [[ $FOUND == 0 ]]
  then
    exit 1
  fi
}
start() {
  coproc bananafd { banana; }
  handle ${bananafd[0]} $1
}
