#!/bin/bash
set -e
set -x
NUM_JOBS=${NUM_JOBS:--j8}
RUN=${RUN:-"ON"}

function make_service() {
  mkdir -p build
  pushd build
  cmake .. "$@"
  make $NUM_JOBS
  popd
}

# check that at least there is a cmake script here
if [ ! -f CMakeLists.txt ]; then
   echo "There must be at least a CMakeLists.txt in service folder"
   exit 1
fi
make_service "$@"

if [[ "$RUN" = "ON" ]]; then
  #sudo mknod /dev/net/tap c 10 200
  BINARY=build/"`cat build/binary.txt`"
  if [[ "$DBG" = "ON" ]]; then
    gdb $BINARY
  else
    $BINARY
  fi
fi
