#################################################
#          IncludeOS SERVICE makefile           #
#################################################

# The name of your service
SERVICE = test_fat16
SERVICE_NAME = FAT16 Test Service

# Your service parts
FILES=fat16.cpp
# Your disk image
DISK=my.disk

# IncludeOS location
ifndef INCLUDEOS_INSTALL
INCLUDEOS_INSTALL=$(HOME)/IncludeOS_install
endif

include $(INCLUDEOS_INSTALL)/Makeseed
