#################################################
#          IncludeOS SERVICE makefile           #
#################################################

# The name of your service
SERVICE = STREAM
SERVICE_NAME = STREAM Memory benchmark

# Your service parts
FILES = service.cpp stream.cpp

# Your disk image
DISK=
MAX_MEM=256

# IncludeOS location
ifndef INCLUDEOS_INSTALL
INCLUDEOS_INSTALL=$(HOME)/IncludeOS_install
endif

include $(INCLUDEOS_INSTALL)/Makeseed
