#! /bin/sh

# in order to be able to find brctl
PATH=$PATH:/sbin:/usr/sbin

set -x

switch=br0


NETWORK=192.168.0.0
NETMASK=255.255.255.0
GATEWAY=192.168.0.1
DHCPRANGE=192.168.53.2,192.168.53.254

if [ -n "$1" ];then
    sleep 0.5s
    sudo tunctl -u `whoami` -t $1
    sudo ifconfig $1 up
    sudo ifconfig br0 $GATEWAY netmask $NETMASK up
    route add -host 192.168.0.11 dev br0
    #sleep 0.5s
    #sudo ip link set $1 up
    sleep 0.5s
    sudo brctl addif $switch $1
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi

