#################################################
#          IncludeOS SERVICE makefile           #
#################################################

# The name of your service
SERVICE = "IncludeOS_service"
SERVICE_NAME = "My\ IncludeOS\ Service"

# Your service parts
FILES = service.cpp
# Your disk image
DISK=

# IncludeOS location
ifndef INCLUDEOS_INSTALL
INCLUDEOS_INSTALL=$(HOME)/IncludeOS_install
endif

include $(INCLUDEOS_INSTALL)/Makeseed
