#################################################
#          IncludeOS SERVICE makefile           #
#################################################

# The name of your service
SERVICE = "Test_UDP"
SERVICE_NAME = "IncludeOS\ UDP\ test"

# Your service parts
FILES = service.cpp

# Your disk image
DISK=

# IncludeOS location
ifndef INCLUDEOS_INSTALL
INCLUDEOS_INSTALL=$(HOME)/IncludeOS_install
endif

include $(INCLUDEOS_INSTALL)/Makeseed
